# Use an official OpenJDK runtime as a parent image
FROM openjdk:11-jre-slim

# Set the working directory to /app
WORKDIR /app

# Copy the packaged Spring Boot application to the container
COPY target/my-spring-boot-app.jar app.jar

# Expose port 8080 for the application
EXPOSE 8080

# Run the Spring Boot application when the container launches
ENTRYPOINT ["java", "-jar", "app.jar"]

